### ISSUE TITLE
Implicitly trusted OIDC issuers are not considered

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/access-token-verifier#10]
The specification [states](https://solid.github.io/solid-oidc/#resource-access-validation) that:

> If the iss claim is different from the domain of the WebID, then the RS MUST check the WebID document for the existence of a statement matching ?`webid <http://www.w3.org/ns/solid/terms#oidcIssuer> ?iss.`

However, we always unconditionally perform this verification:

https://github.com/solid/access-token-verifier/blob/2090eb5d92d3c07fc43cd4c743a6afaca802bb15/src/algorithm/verifySolidAccessToken.ts#L48-L55

As a result, WebID documents without explicit issuers always fail validation, even if using the IDP specific to their WebID.

There are a couple of places where we could fix this; I was thinking about either `verifySolidAccessToken`, `retrieveWebidTrustedOidcIssuers`, or `verifySolidAccessTokenIssuer`.

However, some things are unclear in the spec to me, so I think we need to await resolution of this:
- https://github.com/solid/solid-oidc/issues/51

**Comment by matthieubosquet** [comment]
@RubenVerborgh I answered [here](https://github.com/solid/solid-oidc/issues/51) and [there](https://github.com/w3c/WebID/issues/1#issuecomment-977326427).

Apologies I missed that.

**Comment by RubenVerborgh** [comment]
Thanks, @matthieubosquet. I think we can close this one until the specification has made a decision.
Currently, the behavior seems to be aligned with a literal reading of the spec.
