### ISSUE TITLE
DPoP proof htu parameter seems to match URI without query and fragment parts

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/access-token-verifier#15]
During testing, we saw the following error (IP address changed):

> Error verifying WebID via DPoP-bound access token: The DPoP proof htu parameter doesn't match the HTTP request URI without query and fragment parts.
> Actual: http://1.1.1.1:3000/
> Expected: http://1.1.1.1:3000/?code=AewTYriBRvnAYZAMEpVVtDB5yJbZ6cBopBNtxy7P8rS&state=6e76ec378ac64a118d09a77d4c240710

Unfortunately, I cannot give instructions to reproduce, given that it was a private setup. But given that the match seems to be okay, we might want to double-check the code.

**Comment by RubenVerborgh** [comment]
Also I am not a major fan of the `split`s in https://github.com/solid/access-token-verifier/blob/05713e9b7490d42a43109a499ef769e87d9a8f12/src/algorithm/verifyDpopProofHttpUri.ts#L13

This can easily lead to errors. I think we should use an existing `URL` object (provided by Node) or have a regular expression.

**Comment by RubenVerborgh** [comment]
Note that the htu in this case seemed to contain a query string itself. Is that allowed? Probably not, so the code was correct to throw. Just wonder how we ended up with that `htu` in the first place.

**Comment by matthieubosquet** [comment]
> Note that the htu in this case seemed to contain a query string itself. Is that allowed?

There is nothing saying it is not allowed, but it would never match. So, indeed, the htu is wrong and this is not a [@solid/access-token-verifier](https://github.com/solid/access-token-verifier) bug. If we knew which library issued this access token, we could flag it there.

I would close the issue if you're satisfied with your PR [merged](https://github.com/solid/access-token-verifier/pull/16) and [released](https://github.com/solid/access-token-verifier/releases/tag/1.0.4).

**Comment by RubenVerborgh** [comment]
We have been able to trick Mashlib into this situation; it's part of a bigger issue of running a Solid server over HTTP (as opposed to HTTPS), which I will look into. Thanks!
