### ISSUE TITLE
Authorization header is incorrectly matched as containing one space after the authentication scheme

### ISSUE THREAD

**Issue by matthieubosquet** [solid/access-token-verifier#17]
https://github.com/solid/access-token-verifier/blob/05713e9b7490d42a43109a499ef769e87d9a8f12/src/algorithm/verifySolidAccessToken.ts#L32

As per [the DPoP draft section 7.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-04#section-7.1), one to many spaces are expected:

```abnf
credentials = "DPoP" 1*SP token68
```

**Comment by RubenVerborgh** [comment]
And actually, are we verifying that the header _does_ start with one of those two?

Otherwise, I'd suggest a `/^(DPoP|Bearer) +(\w+)$/.exec`.

**Comment by acoburn** [comment]
Case doesn't matter in the scheme part. 

https://datatracker.ietf.org/doc/html/rfc7235#section-2.1

> It uses a case-
   insensitive token as a means to identify the authentication scheme

**Comment by matthieubosquet** [comment]
Authentication scheme verification https://github.com/solid/access-token-verifier/pull/19 and authorization header parsing https://github.com/solid/access-token-verifier/pull/20 fix [released](https://github.com/solid/access-token-verifier/releases/tag/1.0.5).
