### ISSUE TITLE
Create a v1.0.0 release

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/access-token-verifier#7]
It would be good to create a v1.0.0 release to be included with CSS v1.0.0, such that we can do proper semver from thereon.

Let's:
- [x] Determine what we still need in v1.0.0
  - [x] https://github.com/solid/community-server/issues/718
  - [x] https://github.com/solid/community-server/issues/750 ?
- [x] Create issues and resolve them
- [x] Push v1.0.0 to npm

**Comment by matthieubosquet** [comment]
Pushed 1.0 to facilitate automatic upgrades as per https://github.com/solid/community-server/issues/914#issuecomment-912332420

**Comment by RubenVerborgh** [comment]
🥳
